#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-nodeenv
Version  : 1.7.0
Release  : 45
URL      : https://files.pythonhosted.org/packages/f3/9d/a28ecbd1721cd6c0ea65da6bfb2771d31c5d7e32d916a8f643b062530af3/nodeenv-1.7.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/f3/9d/a28ecbd1721cd6c0ea65da6bfb2771d31c5d7e32d916a8f643b062530af3/nodeenv-1.7.0.tar.gz
Summary  : Node.js virtual environment builder
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-nodeenv-bin = %{version}-%{release}
Requires: pypi-nodeenv-license = %{version}-%{release}
Requires: pypi-nodeenv-python = %{version}-%{release}
Requires: pypi-nodeenv-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(setuptools)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
===========================
        
        ``nodeenv`` (node.js virtual environment) is a tool to create 
        isolated node.js environments.
        
        It creates an environment that has its own installation directories, 
        that doesn't share libraries with other node.js virtual environments.
        
        Also the new environment can be integrated with the environment which was built
        by virtualenv_ (python).

%package bin
Summary: bin components for the pypi-nodeenv package.
Group: Binaries
Requires: pypi-nodeenv-license = %{version}-%{release}

%description bin
bin components for the pypi-nodeenv package.


%package license
Summary: license components for the pypi-nodeenv package.
Group: Default

%description license
license components for the pypi-nodeenv package.


%package python
Summary: python components for the pypi-nodeenv package.
Group: Default
Requires: pypi-nodeenv-python3 = %{version}-%{release}

%description python
python components for the pypi-nodeenv package.


%package python3
Summary: python3 components for the pypi-nodeenv package.
Group: Default
Requires: python3-core
Provides: pypi(nodeenv)
Requires: pypi(setuptools)

%description python3
python3 components for the pypi-nodeenv package.


%prep
%setup -q -n nodeenv-1.7.0
cd %{_builddir}/nodeenv-1.7.0
pushd ..
cp -a nodeenv-1.7.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672293310
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-nodeenv
cp %{_builddir}/nodeenv-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-nodeenv/65f1b0655756044b7fd3f2d81d27cb0b39c1d348 || :
cp %{_builddir}/nodeenv-%{version}/debian-upstream/copyright %{buildroot}/usr/share/package-licenses/pypi-nodeenv/65f1b0655756044b7fd3f2d81d27cb0b39c1d348 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/nodeenv

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-nodeenv/65f1b0655756044b7fd3f2d81d27cb0b39c1d348

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
